### ISSUE TITLE
The fingerprints say "AUR" instead of "MPR"

### ISSUE THREAD

**Issue by gamer4life1** [makedeb/mprweb-historic#5]
![image](https://user-images.githubusercontent.com/42851999/137207131-f1f26b22-093b-4262-b8bb-bc237722c747.png)

^^ shows what you see on the website. If I can figure out how the heck the structure for this repo works, I can try a PR. Otherwise, you'll have to fix it :)

**Comment by hwittenborn** [comment]
Text should be in here if you want to go at it :) https://github.com/makedeb/mprweb/blob/main/web/html/home.php
